important_roi_estimator:
  ros__parameters:
    # ======================
    # Input
    # ======================
    input_topic: "/livox/lidar_perturbed"

    # ======================
    # Binning
    # ======================
    horizontal_fov_deg: 70.4
    vertical_fov_deg: 77.2
    num_horizontal_bins: 128
    num_vertical_bins: 128

    # ======================
    # Importance
    # ======================
    enable_temporal: true
    ema_alpha: 0.05
    min_expected_hits: 1.0
    N_min_compare: 1

    w_s: 0.5
    w_t: 0.5
    roi_top_percent: 5.0

    # ======================
    # Reliability
    # ======================
    w_m: 0.45
    w_r: 0.20
    w_n: 0.35
    dr_scale_m: 0.50
    n_floor: 1.0
    sigmoid_beta: 8.0
    sigmoid_center_c: 0.55
    tau_rel: 0.85

    # ======================
    # Publish (visualization topics)
    # ======================
    publish_maps_as_image: true
    publish_range_hat: false
    publish_range_hat_as_image: true

    # ======================
    # Metrics / Profiling
    # ======================
    metrics_enable: true
    metrics_log_period_frames: 30

    profile_enable: true
    profile_log_period_frames: 30
    profile_warn_ms: 100.0

    # ======================
    # Image Saving (FILE OUTPUT)  ★ここが追加
    # ======================
    save_enable: true
    save_dir: "/home/agx-orin-07/ws_livox/eval/case0_baseline/images"
    save_every_n: 5          # 5フレームに1回保存（10Hzなら0.5秒おき）
    save_start_frame: 1
    save_stop_frame: 0       # 0=無制限
    save_format: "png"       # png / pgm / ppm

    # 何を保存するか
    save_importance: true
    save_reliability: true
    save_range: true
    save_roi_rgb: true       # ROIを色付き（use=緑, alert=赤）で保存
    save_roi_masks: false    # 必要ならtrue（roi_imp/use/alertをmonoで保存）
    save_npy: false          # 必要ならtrue（R/I/Rel等を.npy保存）

